apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: kube-system
parameters:
  mountOptions: vers=3
provisioner: provisioner-jupyterhub
volumeBindingMode: Immediate
