---
- name: Set IP address variables --- master_ip_address
  set_fact: master_ip_address="{{groups['masters'][0]}}"
- name: Set IP address variables --- etcd_ip_address
  set_fact: etcd_ip_address="{{groups['etcd'][0]}}"
  ignore_errors: yes
- name: Set IP address variables --- node_ip_address
  set_fact: node_ip_address={{ hostvars[groups['nodes'][0]]['ansible_default_ipv4']['address'] }}
- name: Set IP address variables --- board_ip_address
  set_fact: board_ip_address={{ hostvars[groups['board'][0]]['ansible_default_ipv4']['address'] }}
  ignore_errors: yes
- name: Set IP address variables --- nfs_server_ip_address
  set_fact: nsf_server_ip_address={{ hostvars[groups['nfs-server'][0]]['ansible_default_ipv4']['address'] }}
  ignore_errors: yes
- name: Set IP address variables --- registry_ip_address
  set_fact: registry_ip_address={{groups['registry'][0]}}
  ignore_errors: yes

