---

- name: copy image to localion
  copy: src={{role_path}}/../../pre-env/images/{{item}} dest={{docker_image_dir}}
  with_items:
    - "k8s-images.tar"

- name: load image
  shell: docker load -i {{docker_image_dir}}/{{item}}
  with_items:
    - "k8s-images.tar"

- name: push k8s images
  shell: docker tag {{item}} {{registry_ip_address}}:5000/k8simage/{{item}}
  with_items:
    - "pause:3.1"
    - "kube-proxy:v1.15.3"
    - "kube-apiserver:v1.15.3"
    - "kube-scheduler:v1.15.3"
    - "kube-controller-manager:v1.15.3" 
    - "coredns:1.3.1"
    - "etcd:3.3.10"
    - "flannel:v0.11.0-amd64"

- name: push image to registry
  shell: docker push {{registry_ip_address}}:5000/k8simage/{{item}}
  with_items:
    - "pause:3.1"
    - "kube-proxy:v1.15.3"
    - "kube-apiserver:v1.15.3"
    - "kube-scheduler:v1.15.3"
    - "kube-controller-manager:v1.15.3"
    - "coredns:1.3.1"
    - "etcd:3.3.10"
    - "flannel:v0.11.0-amd64"
#  shell: /var/lib/sh/run.sh
#  shell: {{shfile_dir}}{{tmp}}{{registry_sh}} {{registy_ip_address}}
#  cmd: {{shfile_dir}}
  
