apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-server
    namespace: kube-system
  nfs:
    path: {{nfs_dir}}
    server: {{nsf_server_ip_address}} 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

