---
- name: install docker-ce
  yum: name=docker-ce state=latest

- name: start docker
  service: name=docker enabled=yes state=started

- name: config daemon.json file
  template: src={{role_path}}/templates/daemon.json dest=/etc/docker/daemon.json

- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: restart docker
  service: name=docker enabled=yes state=restarted

