{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "nexus.name" . }}-service
{{- end }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
    - name: {{ .Values.service.dockerName }}
      port: {{ .Values.service.dockerPort }}
      protocol: TCP
      targetPort: {{ .Values.service.dockerPort }}
    - name: {{ .Values.service.docker1Name }}
      port: {{ .Values.service.docker1Port }}
      protocol: TCP
      targetPort: {{ .Values.service.docker1Port }}
    - name: {{ .Values.service.docker2Name }}
      port: {{ .Values.service.docker2Port }}
      protocol: TCP
      targetPort: {{ .Values.service.docker2Port }}
    - name: {{ .Values.service.docker3Name }}
      port: {{ .Values.service.docker3Port }}
      protocol: TCP
      targetPort: {{ .Values.service.docker3Port }}
  selector:
    app: {{ template "nexus.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.serviceType }}
{{- end}}
