---


- name: push image to registry
  shell: docker pull {{registry_ip_address}}:5000/k8simage/{{item}}
  with_items:
    - "pause:3.1"
    - "kube-proxy:v1.15.3"
    - "kube-apiserver:v1.15.3"
    - "kube-scheduler:v1.15.3"
    - "kube-controller-manager:v1.15.3"
    - "coredns:1.3.1"
    - "etcd:3.3.10"
    - "flannel:v0.11.0-amd64"
#  shell: /var/lib/sh/run.sh
#  shell: {{shfile_dir}}{{tmp}}{{registry_sh}} {{registy_ip_address}}
#  cmd: {{shfile_dir}}
  
