---
- name: copy systemd files to master
  template: src={{role_path}}/templates/{{item}} dest=/var/lib/yaml/
  with_items:
    - "tiller.yaml"
    - "tiller-service.yaml"
    - "fluentd.yaml"
    - "board-clusterrolebinding.yaml"
    - "cadvisor.yaml"
    - "prometheus.yaml"
    - "prometheus2.yaml"
 
- name: copy init file
  copy: src={{role_path}}/files/init.sh dest=/var/lib/yaml/init.sh mode=755

- name: kubectl create -f tiller
  shell: kubectl create -f /var/lib/yaml/{{item}}
  with_items:
    - "tiller.yaml"
    - "tiller-service.yaml"
    - "fluentd.yaml"
    - "board-clusterrolebinding.yaml"
    - "cadvisor.yaml"
    - "prometheus.yaml"
    - "prometheus2.yaml"
    
